version: "3.0"
services:
  database:
    container_name: wedding-db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: weddingDb
    ports:
      - "5432:5432"
    volumes:
      - wedding-data:/var/lib/postgresql/data
volumes:
  wedding-data:
