// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeddingWebsiteCore.DataAccess;

namespace WeddingWebsiteCore.Migrations
{
    [DbContext(typeof(SqlLiteWeddingContext))]
    partial class SqlLiteWeddingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("WeddingWebsiteCore.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnName("State")
                        .HasColumnType("char(2)");

                    b.Property<string>("StreetDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetName")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("AddressId");

                    b.ToTable("addresses");
                });

            modelBuilder.Entity("WeddingWebsiteCore.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("WeddingWebsiteCore.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("AddressId");

                    b.ToTable("events");
                });

            modelBuilder.Entity("WeddingWebsiteCore.Models.Family", b =>
                {
                    b.Property<int>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdditionalGuests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("FamilyId");

                    b.HasIndex("AddressId");

                    b.ToTable("families");
                });

            modelBuilder.Entity("WeddingWebsiteCore.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("FamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FamilyId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsChild")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWeddingMember")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("RsvpId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuestId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("FamilyId1");

                    b.HasIndex("RsvpId")
                        .IsUnique();

                    b.ToTable("guests");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Guest");
                });

            modelBuilder.Entity("WeddingWebsiteCore.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("images");
                });

            modelBuilder.Entity("WeddingWebsiteCore.Models.Registry", b =>
                {
                    b.Property<int>("RegistryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("RegistryId");

                    b.ToTable("registries");
                });

            modelBuilder.Entity("WeddingWebsiteCore.Models.Rsvp", b =>
                {
                    b.Property<int>("RsvpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasResponded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAttending")
                        .HasColumnType("INTEGER");

                    b.HasKey("RsvpId");

                    b.HasIndex("EventId");

                    b.ToTable("rsvps");
                });

            modelBuilder.Entity("WeddingWebsiteCore.Models.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("VendorId");

                    b.HasIndex("AddressId");

                    b.ToTable("vendors");
                });

            modelBuilder.Entity("WeddingWebsiteCore.Models.WeddingMemberRole", b =>
                {
                    b.Property<int>("WeddingMemberRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeddingMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeddingRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WeddingMemberRoleId");

                    b.HasIndex("WeddingMemberId");

                    b.HasIndex("WeddingRoleId");

                    b.ToTable("wedding_member_roles");
                });

            modelBuilder.Entity("WeddingWebsiteCore.Models.WeddingRole", b =>
                {
                    b.Property<int>("WeddingRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("WeddingRoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("wedding_roles");

                    b.HasData(
                        new
                        {
                            WeddingRoleId = 1,
                            Name = "Bride"
                        },
                        new
                        {
                            WeddingRoleId = 2,
                            Name = "Groom"
                        },
                        new
                        {
                            WeddingRoleId = 3,
                            Name = "Maid of Honor"
                        },
                        new
                        {
                            WeddingRoleId = 4,
                            Name = "Best Man"
                        },
                        new
                        {
                            WeddingRoleId = 5,
                            Name = "Bridesmaid"
                        },
                        new
                        {
                            WeddingRoleId = 6,
                            Name = "Groomsman"
                        },
                        new
                        {
                            WeddingRoleId = 7,
                            Name = "Flower Girl"
                        },
                        new
                        {
                            WeddingRoleId = 8,
                            Name = "Ring Bearer"
                        },
                        new
                        {
                            WeddingRoleId = 9,
                            Name = "Officiant"
                        },
                        new
                        {
                            WeddingRoleId = 10,
                            Name = "Father of the Bride"
                        },
                        new
                        {
                            WeddingRoleId = 11,
                            Name = "Mother of the Bride"
                        },
                        new
                        {
                            WeddingRoleId = 12,
                            Name = "Father of the Groom"
                        },
                        new
                        {
                            WeddingRoleId = 13,
                            Name = "Mother of the Groom"
                        },
                        new
                        {
                            WeddingRoleId = 14,
                            Name = "Grandmother of the Bride"
                        },
                        new
                        {
                            WeddingRoleId = 15,
                            Name = "Grandfather of the Bride"
                        },
                        new
                        {
                            WeddingRoleId = 16,
                            Name = "Grandmother of the Groom"
                        },
                        new
                        {
                            WeddingRoleId = 17,
                            Name = "Grandfather of the Groom"
                        },
                        new
                        {
                            WeddingRoleId = 18,
                            Name = "Junior Bridesmaid"
                        },
                        new
                        {
                            WeddingRoleId = 19,
                            Name = "Usher"
                        });
                });

            modelBuilder.Entity("WeddingWebsiteCore.Models.WeddingMember", b =>
                {
                    b.HasBaseType("WeddingWebsiteCore.Models.Guest");

                    b.ToTable("wedding_members");

                    b.HasDiscriminator().HasValue("WeddingMember");
                });

            modelBuilder.Entity("WeddingWebsiteCore.Models.Event", b =>
                {
                    b.HasOne("WeddingWebsiteCore.Models.Address", "Address")
                        .WithMany("Events")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeddingWebsiteCore.Models.Family", b =>
                {
                    b.HasOne("WeddingWebsiteCore.Models.Address", "Address")
                        .WithMany("Families")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeddingWebsiteCore.Models.Guest", b =>
                {
                    b.HasOne("WeddingWebsiteCore.Models.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeddingWebsiteCore.Models.Family", null)
                        .WithMany("Children")
                        .HasForeignKey("FamilyId1");

                    b.HasOne("WeddingWebsiteCore.Models.Rsvp", "Rsvp")
                        .WithOne("Guest")
                        .HasForeignKey("WeddingWebsiteCore.Models.Guest", "RsvpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeddingWebsiteCore.Models.Rsvp", b =>
                {
                    b.HasOne("WeddingWebsiteCore.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeddingWebsiteCore.Models.Vendor", b =>
                {
                    b.HasOne("WeddingWebsiteCore.Models.Address", "Address")
                        .WithMany("Vendors")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WeddingWebsiteCore.Models.WeddingMemberRole", b =>
                {
                    b.HasOne("WeddingWebsiteCore.Models.WeddingRole", "WeddingRole")
                        .WithMany("WeddingMemberRoles")
                        .HasForeignKey("WeddingMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeddingWebsiteCore.Models.WeddingMember", "WeddingMember")
                        .WithMany("WeddingMemberRoles")
                        .HasForeignKey("WeddingRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
